blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls')),
    path('editorjs/', include('django_editorjs_fields.urls')),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogApp/urls.py
from django.urls import path
from . import views

app_name = "blogApp"

urlpatterns = [
    path('',views.index,name="index"),
    path("detail/<int:post_id>/",views.datail,name="detail"),
    path("contact/",views.contact,name="contact"),
]

blogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django_editorjs_fields import EditorJsTextField


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200)
    description = EditorJsTextField()
    image = models.ImageField(upload_to='postImages/')
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title




class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.CharField(max_length=360)
    created_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.name.upper()}"

blogApp/forms.py
from django import forms



class ContactForm(forms.Form):
    name = forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=200,widget=forms.EmailInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

blogApp/views.py
from django.shortcuts import render , get_object_or_404 ,redirect
from django.http import HttpResponse
from django.utils import datetime_safe
from django.core.paginator import Paginator
from .models import Post , Contact
from .forms import ContactForm

 
# common views data
common_current_date = datetime_safe.datetime.now()


# Create your views here.

def index(request):
    latest_posts = Post.objects.order_by('-published_date')

    paginator = Paginator(latest_posts, 5)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    page_conf = {
        'title_tag' : "BlogApp - Home",
        'title_page' : "Blog App",
        'page_explain' : "Hello and welcome to this blog",
        'current_date' : common_current_date,
        'data' : page ,
        
    }

    return render(request, 'blogApp/index.html',context=page_conf)




def datail(request , post_id):
    post = get_object_or_404(Post,pk=post_id)
    #post = {'post' : post}


    page_conf = {
        'title_tag' : post.title,
        'title_page' : post.title,
        'current_date' : post.published_date,
        'post' : post ,
        'page_head_image' : post.image
    }

    return render(request, 'blogApp/detail.html',context=page_conf)




def contact(request):

    if request.method == 'GET':
        form = ContactForm()
        form ={'form':form}
        return render(request, 'blogApp/contact.html',context=form)
    else:
        # Get form data
        form = ContactForm(request.POST)

        if form.is_valid():
            name = form.data['name']
            email = form.data['email']
            message = form.data['message']

            new_msg = Contact()
            new_msg.name = name
            new_msg.email = email
            new_msg.message = message

        
            new_msg.save()


            return redirect('blogApp:index')

            

        return render(request, 'blogApp/contact.html')        

templates/blogApp/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blogApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{{title_tag}}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        
        <link href="{% static 'blogApp/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
       
        <!-- Navs -->
        {% include 'blogApp/navs.html' %}





        
        {% if page_head_image %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url({{page_head_image.url}}) ">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{title_page}}</h1>
                            <br>
                            <span class="subheading">{{page_explain}}</span>
                            <br>
                            <span class="subheading">{{current_date}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>


        {% endif %}



        
        {% if not page_head_image %}

        <header class="masthead" style="background-image: url({% static 'blogApp/assets/img/home-bg.jpg' %}) ">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{title_page}}</h1>
                            <br>
                            <span class="subheading">{{page_explain}}</span>
                            <br>
                            <span class="subheading">{{current_date}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endif %}











        <!-- Main Content-->


        {% block mainContent %}

        {% endblock mainContent %}




        
        <!-- Footer-->
        {% include 'blogApp/footer.html' %}
      




        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blogApp/contact.html
{% extends 'blogApp/base.html' %}

{% block mainContent %}

        <!-- Main Content-->
        <main class="mb-4">
            
            

            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                      

                
                            <form id="contactForm" method="post" action="{% url 'blogApp:contact' %}">

                                {% csrf_token %}
                                <div class="form-floating">
                                {{form.name}}   
                                <label for="name">Name</label>
                                
                                </div>
                                <div class="form-floating">
                                    {{form.email}}
                                    <label for="email">Email address</label>
        
                                </div>
                                
                                <div class="form-floating">
                                    {{form.message}}
                                    <label for="message">Message</label>
                                   
                                </div>
                                <br />
                            
                                
                                
                                <input type="submit" value="Submit" class="btn btn-info text-white">



                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% endblock mainContent %}

templates/blogApp/detail.html
{% extends 'blogApp/base.html' %}


{% block mainContent %}

        <!-- Post Content-->
        <article class="mb-4" >
            <div class="container px-4 px-lg-5">
                
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {% load editorjs %}
                        {{post.description | editorjs}}
                        <br>
                        <br>
                        by <small class="text-info">{{post.author}}</small>
                        <br>
                        on <small class="text-info">{{post.published_date}}</small>
                        <br>
                        
                        </p>
                    </div>
                </div>
            </div>
        </article>
        

{% endblock mainContent %}

templates/blogApp/footer.html
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://t.me/amirkho_eng" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-telegram fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://instagram.com/amirkho.ir" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/amirkho-py" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; blogApp by Django & Bootstrap 2023</div>
            </div>
        </div>
    </div>
</footer>

templates/blogApp/index.html
{% extends 'blogApp/base.html' %}


{% block mainContent %}


<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">


            {% for post in data %}

            <!-- Post preview-->
            <div class="post-preview">
                <a href="{% url 'blogApp:detail' post.id %}">
                    <h2 class="post-title">{{post.title}}</h2>
                    {% load editorjs %}
                    <h3 class="post-subtitle">{{post.description|editorjs|truncatewords:2}}</h3>
                </a>
                <p class="post-meta">
                    Posted by
                    <a href="#">{{post.author}}</a>
                    {{post.published_date}}
                </p>
            </div>

            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}



            
           
            
          

            <!-- Pager-->

            {% if data.has_previous %}
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="?page={{data.previous_page_number}}">← New Posts </a></div>
            {% endif %}

            {% if data.has_next %}
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="?page={{data.next_page_number}}">Older Posts →</a></div>
            {% endif %}

            



        </div>
    </div>
</div>


{% endblock mainContent %}

templates/blogApp/navs.html
 <!-- Navigation-->
 <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'blogApp:index'%}">Blog App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogApp:index'%}">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogApp:contact'%}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>